runtime: php
env: flex

runtime_config:
  document_root: public

handlers:
  - url: /artisan
    script: public/index.php
    login: admin
    secure: always

  - url: /.*
    script: public/index.php

# Ensure we skip ".env", which is only for local development
skip_files:
  - .env

env_variables:
  # Put production environment variables here.
  APP_LOG: errorlog
  APP_KEY: base64:+sNJxNSGDLONbWNyOlVY/Sivla+JR+rF8ikvEwqxVZY=
  STORAGE_DIR: /tmp
  CACHE_DRIVER: database
  SESSION_DRIVER: database

  ## Set these environment variables according to your CloudSQL configuration.
  DB_HOST: localhost
  DB_DATABASE: multiauth2
  DB_USERNAME: root
  DB_PASSWORD: kaigangames-project
  DB_SOCKET: "/cloudsql/bukufi:asia-northeast1:cloud-database"

# Use the connection name obtained when configuring your Cloud SQL instance.
beta_settings:
  cloud_sql_instances: bukufi:asia-northeast1:cloud-database